### ISSUE TITLE
PR #19 missing in 2.3.0 release

### ISSUE THREAD

**Issue by mfiebig** [CocoaPods/fourflusher#23]
Hi,

#19 is missing in the 2.3.0. The PR is merged in the branch `stable-2-2`, though no release containing the fix is available. It seems that `stable-2-2` is not merged into `stable-2-3`.

I have no rights to fix this, but if I can help somehow, tell me :)

**Comment by dnkoutso** [comment]
@mfiebig i believe you are correct. Really sorry for this ill take care of it.

**Comment by dnkoutso** [comment]
Released in 2.3.1

**Comment by mfiebig** [comment]
> Really sorry for this ill take care of it.

Don't worry about it! Thanks for your awesome work!
